name: Deploy Vue.js Frontend Service

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      systemctl_service_name: frontend   # Name of the frontend service (ensure it matches your service name)
      message: |
        [${{ github.event.head_commit.committer.name }}](https://github.com/${{ github.event.head_commit.committer.username }}) pushed new commit:
        `[ ${{ github.event.head_commit.message }} ]`
        to [${{ github.event.repository.name }}](https://github.com/${{ github.event.repository.html_url }}) 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust this to the version you're using for Vue.js

      - name: Install dependencies
        run: npm install

      - name: Build the Vue.js application
        run: npm run build  # Builds the application, places output in the dist/ folder

      - name: Stop Vue.js service (if running)
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl stop ${{ env.systemctl_service_name }}  # Stop service on your server
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Copy build files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: dist/*  # Your build output
          target: "/var/www/frontend"  # Target directory on the server
          overwrite: true
          rm: false
          debug: true

      - name: Start Vue.js service
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl start --no-block ${{ env.systemctl_service_name }}  # Restart the service
          host: ${{ secrets.SSH_HOST }}
          port: 22
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}  # Telegram chat ID (stored in secrets)
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Telegram bot token (stored in secrets)
          message: ${{ env.message }}  # The commit message built earlier
          format: markdown
          disable_web_page_preview: true
